### ISSUE TITLE
Seems like the dataset is damaged

### ISSUE THREAD

**Issue by AnonymousPomp** [ktaebum/AttentionedDeepPaint#16]
When I tried to unzip the kaggle dataset (https://www.kaggle.com/ktaebum/anime-sketch-colorization-pair), I've discovered that the dataset has been damaged.
It doesn't even unzip "val" folder.

I've tried downloading it from different internet, and even tried to download it from the old dataset (https://www.kaggle.com/ktaebum/animesketchcolorpair)

My environment is Windows 10 Home version 1903 for OS
and Bandizip for unzipper.

**Comment by ktaebum** [comment]
Thanks for reporting
Could you explain error (or error message) in more detail?
I just downloaded the dataset and ran the program, and it does not report any error.

I think that error might occurs due to Window system or Bandizip program since I did not check in Window environment (I only checked for Ubuntu 16.04 or later)

**Comment by AnonymousPomp** [comment]
Thank you for such a fast reply :)
Here is how the error looks like:
![제목 없음](https://user-images.githubusercontent.com/40858122/61629662-17840a00-acb8-11e9-9e09-6d8c32a02eca.png)

the image is corrupted from data/train/2850149.png of train images
and the entire val folder

**Comment by otori-bird** [comment]
you can try with winrar not banzip

**Comment by AnonymousPomp** [comment]
works like a charm with WinRAR.
but is too slow.
I suggest using an unzipper with multithreading if you have the same error.
Thank you all!!
